### ISSUE TITLE
homebrew compilation fails

### ISSUE THREAD

**Issue by ahundt** [feelpp/feelpp#513]
I was following the homebrew instructions and the installation failed.

https://gist.github.com/3e17d2f2375f9d1901a4

I used the following command from the instructions:

    brew tap feelpp/science && brew install feelpp

I found the instructions at https://github.com/feelpp/feelpp/wiki/Homebrew

**Comment by vhuber** [comment]
Hello Andrew,

The documentation is [here](http://www.feelpp.org/docs/develop/BuildingP.html#Homebrew).
It seems you have a trouble with Petsc.

May you please check that all dependancies are installed with `brew info feelpp` ?

**Comment by ahundt** [comment]
It looks like all of the dependencies are installed unless if one was installed previously and thus wasn't built with the correct feature flags. I did make sure boost is installed with mpi. 
```
○ brew info feelpp
feelpp: stable 0.99.0-final.1, HEAD
http://www.feelpp.org
Not installed
From: https://github.com/feelpp/homebrew-science/blob/master/feelpp.rb
==> Dependencies
Build: cmake ✔
Required: autoconf ✔, automake ✔, libtool ✔, cln ✔, eigen ✔, scalapack ✔, petsc ✔, boost ✔
Recommended: gmsh ✔, ann ✔, glpk ✔
Optional: doxygen ✔
==> Options
--with-doxygen
	Build with doxygen support
--without-ann
	Build without ann support
--without-glpk
	Build without glpk support
--without-gmsh
	Build without gmsh support
--HEAD
	Install HEAD version
```

It appears there are some warnings about petsc using a different c++ standard library, perhaps that is the source of the issue?

```
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.5.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-3.5.2.tar.gz
==> Patching
==> ./configure CC=/usr/local/bin/mpicc CXX=/usr/local/bin/mpicxx F77=/usr/local/bin/mpif77 FC=/
==> make all
==> make test 2>&1 | tee make-check-real.log
==> Completed test examples
==> make install
==> ./configure CC=/usr/local/bin/mpicc CXX=/usr/local/bin/mpicxx F77=/usr/local/bin/mpif77 FC=/
==> make all
==> make test 2>&1 | tee make-check-complex.log
==> Completed test examples
==> make install
Warning: petsc dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
==> Caveats
    Set PETSC_DIR to /usr/local/Cellar/petsc/3.5.2_2/real or /usr/local/Cellar/petsc/3.5.2_2/complex.
    Fortran module files are in
      /usr/local/Cellar/petsc/3.5.2_2/real/include and /usr/local/Cellar/petsc/3.5.2_2/complex/include
==> Summary
🍺  /usr/local/Cellar/petsc/3.5.2_2: 860 files, 40M, built in 3.5 minutes
```

**Comment by aancel** [comment]
@ahundt I managed to reproduce your issue wth version 0.99.
The next release 0.100, currently in beta (https://github.com/feelpp/feelpp/releases/), doesn't work either as of now for homebrew (It manages to go through the cmake step, but fails at building). We'll fix this for the final release.
For now, a workaround would be to use the develop version of feel++. First, you need to install the dependencies of feel++ with:   
```
brew install --only-dependencies feelpp
```
and build feel++ from a clone of the develop branch.

**Comment by milicchio** [comment]
@aancel I've tried this workaround but it fails compiling:
```
/Users/sensei/Downloads/feelpp/feel/feelalg/preconditionerpetsc.cpp:2113:26: error: 
      use of undeclared identifier 'MatCreateVecs'
            this->check( MatCreateVecs(A,&scaleDiag,NULL) );
                         ^
[ 58%] Building CXX object feel/CMakeFiles/feelpp.dir/feeldiscr/stencil.cpp.o
[ 58%] Building CXX object feel/CMakeFiles/feelpp.dir/feeldiscr/oseendata.cpp.o
1 error generated.
make[2]: *** [feel/CMakeFiles/feelpp.dir/feelalg/preconditionerpetsc.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [feel/CMakeFiles/feelpp.dir/all] Error 2
make: *** [all] Error 2

% git checkout
Your branch is up-to-date with 'origin/develop'.
```

**Comment by prj-** [comment]
Your compilation failure should be fixed now @milicchio, sorry about that.

**Comment by milicchio** [comment]
Thanks @prj-, however, it seems it fails now with CMake:

```
 CMake Error at quickstart/CMakeLists.txt:42 (add_custom_target):
   add_custom_target cannot create target "check" because another target with
   the same name already exists.  The existing target is a custom target
   created in source directory "/Users/sensei/Downloads/feelpp".  See
   documentation for policy CMP0002 for more details.
```

**Comment by prj-** [comment]
This is not specific to your installation, something is wrong inside the `feelpp/quickstart` repository, cf. the Travis build here https://travis-ci.org/feelpp/feelpp/jobs/50058547#L1734. This should be fixed rather soon.

**Comment by milicchio** [comment]
Thanks, @prj-. Since I am working with others that are not really compilation-savvy, I hope homebrew's package will work very soon.

Thanks!

**Comment by prj-** [comment]
This is fixed now, everything should work out OK. Homebrew's package should come out soon.

**Comment by milicchio** [comment]
Unfortunately, I cannot still compile it.

```
[ 91%] Building CXX object feel/CMakeFiles/feelpp.dir/feelpde/boundaryconditions.cpp.o
make[2]: *** No rule to make target `/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib', needed by `feel/libfeelpp.1.0.0.dylib'.  Stop.
make[1]: *** [feel/CMakeFiles/feelpp.dir/all] Error 2
make: *** [all] Error 2

% git log | head
commit c4950dbce1a170db4236f41c3c4bdf42dfccdaeb
Merge: bcacc22 3be2d48
Author: Alexandre Ancel <alexandre.ancel@cemosis.fr>
Date:   Tue Feb 10 09:57:22 2015 +0100

    Merge branch 'develop' of https://github.com/feelpp/feelpp into develop

commit bcacc22e43503b3d5e858f30353476a5e570dfd3
Author: Alexandre Ancel <alexandre.ancel@cemosis.fr>
Date:   Tue Feb 10 09:55:55 2015 +0100
```

Can I help somehow?

**Comment by prj-** [comment]
Please try `brew cleanup` and then delete the CMake cache and recompile from scratch.

**Comment by milicchio** [comment]
Hello @prj-, I've just done a complete cleanup, but the error remains. I don't know why it searches for Python 2.7.8_2, while the correct version is 2.7.9. Here's the complete log:

```
% brew cleanup
Warning: Skipping (old) /usr/local/Cellar/mpfr/3.1.2-p8 due to it being linked

% cd build

% rm -rf *
zsh: sure you want to delete all the files in /Users/sensei/Downloads/feelpp/build [yn]? y

% ls -la
total 0
drwxr-xr-x   2 sensei  staff    68 Feb 10 15:16 ./
drwxr-xr-x  39 sensei  staff  1326 Feb  9 11:24 ../

% cmake ..
-- [feelpp] use new policy CMP0022
-- [feelpp] use NEW policy CMP0038
-- [feelpp] use NEW policy CMP0042
-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/sensei/Downloads/feelpp/build

% make
[  0%] Generating function.h
[  0%] Generating function.cpp
Scanning dependencies of target feelpp_ginac
[  0%] Building CXX object contrib/ginac/ginac/CMakeFiles/feelpp_ginac.dir/add.cpp.o
[  2%] Building CXX object contrib/ginac/ginac/CMakeFiles/feelpp_ginac.dir/archive.cpp.o
...
[ 91%] Building CXX object feel/CMakeFiles/feelpp.dir/feelpde/reinit_fms_inst_3d.cpp.o
[ 91%] Building CXX object feel/CMakeFiles/feelpp.dir/feelpde/boundaryconditions.cpp.o
make[2]: *** No rule to make target `/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib', needed by `feel/libfeelpp.1.0.0.dylib'.  Stop.
make[1]: *** [feel/CMakeFiles/feelpp.dir/all] Error 2
make: *** [all] Error 2
```
Let me know if I can see something.

Thanks & Cheers!

**Comment by aancel** [comment]
@milicchio Can you tell us a bit more about hat is happening in the `...`of the cmake process, there should be some references to python libraries ? Do it find the right ones ? (appently not)

**Comment by milicchio** [comment]
As far as I see, CMake finds two Python installations, the interpreter from Homebrew and the libraries from the system, and gets confused:
```
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.9")
-- Python 2 detected: No need to patch
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.6")
-- [feelpp] PythonLibs: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Python.framework/Headers /usr\
/lib/libpython2.7.dylib
-- [feelpp] Found python version 2.7
```
Full output here: https://gist.github.com/milicchio/06ffd732420895d615bd

**Comment by prudhomm** [comment]
Hello 
I just uploaded the latest beta release on github and updated the formula for feelpp as well as sync with the homebrew mother ship. Now things should work smoothly.
you need first to upgrade your homebrew installation.

Let us know how it works.

**Comment by milicchio** [comment]
Hi, no, it doesn't work. I tried both the new homebrew formula and the latest developer's commits.

The developer branch fails always with Python, as well as homebrew.

Here's the transcript of the developer code: https://gist.github.com/milicchio/13fa7f7f8a3126caf503

Here's the transcript of the homebrew formula with gist-logs: https://gist.github.com/anonymous/6afb633795ddda5b72cb

Thanks!

**Comment by prudhomm** [comment]
it seems that your python installation has issues.
what gives `brew list python`
and what is the content of `/usr/local/Cellar/python/`

**Comment by milicchio** [comment]
Yes, I have (as I think all users) two Python installations, the system and homebrew's.

This is homebrew:
```
% ls /usr/local/Cellar/python 
2.7.9/

% ls /usr/local/Cellar/python/2.7.9 
Frameworks/           LICENSE               bin/
IDLE.app/             Python Launcher.app/  libexec/
INSTALL_RECEIPT.json  README                share/

% ls -l /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib
total 8
lrwxr-xr-x    1 sensei  admin      9 Feb  4 13:13 libpython2.7.dylib@ -> ../Python
drwxr-xr-x    5 sensei  admin    170 Feb  4 13:13 pkgconfig/
drwxr-xr-x  650 sensei  admin  22100 Feb  4 13:13 python2.7/

% brew list python
/usr/local/Cellar/python/2.7.9/bin/2to3
/usr/local/Cellar/python/2.7.9/bin/2to3-2
/usr/local/Cellar/python/2.7.9/bin/2to3-2.7
/usr/local/Cellar/python/2.7.9/bin/easy_install
/usr/local/Cellar/python/2.7.9/bin/easy_install-2.7
/usr/local/Cellar/python/2.7.9/bin/idle
/usr/local/Cellar/python/2.7.9/bin/idle2
/usr/local/Cellar/python/2.7.9/bin/idle2.7
/usr/local/Cellar/python/2.7.9/bin/pip
/usr/local/Cellar/python/2.7.9/bin/pip2
/usr/local/Cellar/python/2.7.9/bin/pip2.7
/usr/local/Cellar/python/2.7.9/bin/pydoc
/usr/local/Cellar/python/2.7.9/bin/pydoc2
/usr/local/Cellar/python/2.7.9/bin/pydoc2.7
/usr/local/Cellar/python/2.7.9/bin/python
/usr/local/Cellar/python/2.7.9/bin/python-config
/usr/local/Cellar/python/2.7.9/bin/python2
/usr/local/Cellar/python/2.7.9/bin/python2-config
/usr/local/Cellar/python/2.7.9/bin/python2.7
/usr/local/Cellar/python/2.7.9/bin/python2.7-config
/usr/local/Cellar/python/2.7.9/bin/pythonw
/usr/local/Cellar/python/2.7.9/bin/pythonw2
/usr/local/Cellar/python/2.7.9/bin/pythonw2.7
/usr/local/Cellar/python/2.7.9/bin/smtpd.py
/usr/local/Cellar/python/2.7.9/bin/smtpd2.7.py
/usr/local/Cellar/python/2.7.9/bin/smtpd2.py
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/ (5044 files)
/usr/local/Cellar/python/2.7.9/IDLE.app/Contents/ (8 files)
/usr/local/Cellar/python/2.7.9/libexec/pip/ (512 files)
/usr/local/Cellar/python/2.7.9/libexec/setuptools/ (251 files)
/usr/local/Cellar/python/2.7.9/Python Launcher.app/Contents/ (17 files)
/usr/local/Cellar/python/2.7.9/share/man/ (3 files)
/usr/local/Cellar/python/2.7.9/share/python/ (315 files)
```
My homebrew is clean and updated:
```
% brew outdated

% brew prune
Pruned 0 dead formulae
Tapped 444 formulae
Pruned 0 symbolic links and 2 directories from /usr/local

% brew cleanup
Warning: Skipping (old) /usr/local/Cellar/mpfr/3.1.2-p8 due to it being linked

% brew doctor
Your system is ready to brew.
```
