### ISSUE TITLE
Review and fix CRB codes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#843]
Some CRB codes are not compiling. @cdaversin could you review the codes and fix them.
We discuss in feelpp/crb the problematic codes.
I would like to ship a docker image soon for crb and soon for chorus and 4fastsim.
chorus and 4fastsim will depend on crb

/cc @feelpp/crb

**Comment by cdaversin** [comment]
@prudhomm All CRB codes in applications/crb are now compiling (at least with clang 3.9). I'm now checking that they run correctly.
/cc @feelpp/crb

**Comment by cdaversin** [comment]
Regarding heat1d application : The run using SCM (`error-type=1`) works only in sequential.
In parallel, I obtain this error : 
```
[0]PETSC ERROR: No support for this operation for this object type
[0]PETSC ERROR: You chose to solve linear systems with a factorization, but in parallel runs you need to select an external package;
```
This problem comes from the call of the `eigs` function in `crbscm.hpp`. 
I identified that it comes from the use of `TransformationShiftInvert` (parameter `_transform=SINVERT` is the `eigs` function).

I've found a way to fix this problem by using the option `-st_pc_factor_mat_solver_package mumps`. This select an external package for spectral transformations, as asked in the error message).
I have also noticed that this option is used in the test associated with the `eigs` function (`feelpp_test_eigs`), to deal with this problem I suppose.
```
feelpp_add_test( eigs CLI "-st_pc_factor_mat_solver_package mumps" )
```
@prudhomm @vincentchabannes Maybe I can add this option to the configuration file for heat1d, or I wonder if it is possible to force this option directly in cmake (as for the previous test) ? Why do you think ?

**Comment by jbwahl** [comment]
related to issue #719

**Comment by cdaversin** [comment]
All CRB codes in `applications/crb` are now running without crash, except when using SCM in parallel (see previous comment and #719 ). But this should be fixed by #848.
/cc @feelpp/crb

**Comment by prudhomm** [comment]
should we close the issue ? 
what is required to run/compile all application now automatically ?

**Comment by cdaversin** [comment]
Almost all CRB codes in `applications/crb` runs correctly in sequential and in parallel. The problem with SCM in parallel is now fixed thanks to the merge of #848. Only eads models crash in parallel, due to the use of periodic dofs (the problem comes with the call of `DofTable<>::buildPeriodicDofMap()`). But they work in sequential.

**Comment by prudhomm** [comment]
@vincentchabannes I assigned this task too. at the same time we should start writing the commands in asciidoc to run the tests. 
I propose that we use the `README.adoc` in each testcase directory which will then be imported by book.feelpp.org

**Comment by prudhomm** [comment]
all the codes are up and running @vincentchabannes ?
should some of them be disabled until they are fixed ?

**Comment by prudhomm** [comment]
all the crb codes are now compiling. 
We are still missing some documentation see feelpp/book.feelpp.org#27
